trigger:
- develop
- master

pr:
- develop

variables:
  - group: "Generic Build Variables"

steps:
- checkout: self
  clean: true
  submodules: true
  persistCredentials: true

- task: UseDotNet@2 
  displayName: ".NET Core 3.1.x"
  inputs:
    version: '3.1.x'
    packageType: sdk
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: PowerShell@2
  displayName: Pre initialization
  inputs:
      filePath: ./pre.ps1
      pwsh: true
  env:
      GITHUB_API_TOKEN: $(GITHUB-API-TOKEN)
      GITHUB_PASSWORD: $(GITHUB-PASSWORD)
      GITHUB_USERNAME: $(GITHUB-USERNAME)

- task: PowerShell@2
  displayName: BuildPackagePublish
  inputs:
      filePath: './build.ps1'
      arguments: '-target "BuildPackagePublish" -InformationAction Continue -Verbosity $(Verbosity)'
      pwsh: true
  env:
      GITHUB_API_TOKEN: $(GITHUB-API-TOKEN)
      GITHUB_PASSWORD: $(GITHUB-PASSWORD)
      GITHUB_USERNAME: $(GITHUB-USERNAME)
      JENKINS_HOME: "~/"
